### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by djames1** [AdelieLinux/gcompat#2]
Please release version 0.0.2 soon. That way we can package changes that have been done since 0.0.1.

**Comment by awilfox** [comment]
I have no idea how this repo ended up with an issue tracker or merge request tool.  This repository is just a mirror repo for [our GitLab instance](https://code.foxkit.us/adelie/gcompat); issues should be filed at [our actual issue tracker](https://bts.adelielinux.org/enter_bug.cgi?product=gcompat) otherwise we will never see them.

I will clarify the contribution guide to make this clear, and remove the ability to file issues here.

I'll ship 0.0.2 after I ensure the isnan/isinf shims are working properly and add the __libc allocator interfaces that a few apps seem to be expecting.
